// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package usersrv

import (
	"context"

	"im/app/user/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FindUserReq     = pb.FindUserReq
	FindUserResp    = pb.FindUserResp
	GetUserInfoReq  = pb.GetUserInfoReq
	GetUserInfoResp = pb.GetUserInfoResp
	LoginReq        = pb.LoginReq
	LoginResp       = pb.LoginResp
	RegisterReq     = pb.RegisterReq
	RegisterResp    = pb.RegisterResp
	Request         = pb.Request
	Response        = pb.Response
	User            = pb.User

	UserSrv interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		FindUser(ctx context.Context, in *FindUserReq, opts ...grpc.CallOption) (*FindUserResp, error)
	}

	defaultUserSrv struct {
		cli zrpc.Client
	}
)

func NewUserSrv(cli zrpc.Client) UserSrv {
	return &defaultUserSrv{
		cli: cli,
	}
}

func (m *defaultUserSrv) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := pb.NewUserSrvClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultUserSrv) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewUserSrvClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUserSrv) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := pb.NewUserSrvClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUserSrv) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := pb.NewUserSrvClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUserSrv) FindUser(ctx context.Context, in *FindUserReq, opts ...grpc.CallOption) (*FindUserResp, error) {
	client := pb.NewUserSrvClient(m.cli.Conn())
	return client.FindUser(ctx, in, opts...)
}
